# Generated by Django 4.0.4 on 2022-05-12 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=50)),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('booked', 'booked'), ('running', 'running'), ('completed', 'completed')], default='booked', max_length=255)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='slots.slot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
